spring:
  application:
    name: eventsql-benchmarks-app
  threads:
    virtual:
      enabled:
        true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]

events:
  data-sources:
    - url: "${DB0_URL:jdbc:postgresql://localhost:5432/events}"
      username: "${DB0_USERNAME:events}"
      password: "${DB0_PASSWORD:events}"
      connections: 10
      enabled: ${DB0_ENABLED:true}
    - url: "${DB1_URL:jdbc:postgresql://localhost:5433/events}"
      username: "${DB1_USERNAME:events}"
      password: "${DB1_PASSWORD:events}"
      connections: 10
      enabled: ${DB1_ENABLED:false}
    - url: "${DB2_URL:jdbc:postgresql://localhost:5434/events}"
      username: "${DB2_USERNAME:events}"
      password: "${DB2_PASSWORD:events}"
      connections: 10
      enabled: ${DB2_ENABLED:false}
  account-created-topic:
    name: "account_created"
    partitions: 10
  account-created-topic-dlt:
    name: "${events.account-created-topic.name}_dlt"
    partitions: 10
  account-created-consumers:
    - topic: "${events.account-created-topic.name}"
      partitioned: true
      name: "benchmarks-consumer"
